# 1
music.play_tone(494, music.beat(BeatFraction.HALF))
pause(75)
music.play_tone(494, music.beat(BeatFraction.HALF))
pause(75)
music.play_tone(494, music.beat(BeatFraction.QUARTER))
pause(75)
music.play_tone(494, music.beat(BeatFraction.HALF))
pause(75)
music.play_tone(494, music.beat(BeatFraction.HALF))
pause(50)
# 2
music.play_tone(659, music.beat(BeatFraction.HALF))
pause(50)
music.play_tone(659, music.beat(BeatFraction.HALF))
pause(50)
music.play_tone(659, music.beat(BeatFraction.HALF))
pause(50)
# 3
music.play_tone(587, music.beat(BeatFraction.HALF))
pause(25)
music.play_tone(587, music.beat(BeatFraction.HALF))
pause(25)
music.play_tone(587, music.beat(BeatFraction.HALF))
pause(50)
music.play_tone(440, music.beat(BeatFraction.HALF))
pause(25)
music.play_tone(494, music.beat(BeatFraction.HALF))