// 1
music.playTone(494, music.beat(BeatFraction.Half))
pause(75)
music.playTone(494, music.beat(BeatFraction.Half))
pause(75)
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(75)
music.playTone(494, music.beat(BeatFraction.Half))
pause(75)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
// 2
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
// 3
music.playTone(587, music.beat(BeatFraction.Half))
pause(25)
music.playTone(587, music.beat(BeatFraction.Half))
pause(25)
music.playTone(587, music.beat(BeatFraction.Half))
pause(50)
music.playTone(440, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
// 1
music.playTone(494, music.beat(BeatFraction.Half))
pause(75)
music.playTone(494, music.beat(BeatFraction.Half))
pause(75)
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(75)
music.playTone(494, music.beat(BeatFraction.Half))
pause(75)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
// 2
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
// 3
music.playTone(587, music.beat(BeatFraction.Half))
pause(25)
music.playTone(587, music.beat(BeatFraction.Half))
pause(25)
music.playTone(587, music.beat(BeatFraction.Half))
pause(50)
music.playTone(440, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(494, music.beat(BeatFraction.Half))
pause(50)
music.playTone(659, music.beat(BeatFraction.Half))
pause(50)
// 1
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(10)
// 1
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(10)
// 1
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(10)
// 1
music.playTone(494, music.beat(BeatFraction.Quarter))
pause(10)
// 1
music.playTone(494, music.beat(BeatFraction.Half))
